src/books/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

from carts.views import *

from .views import home_page, about_page, contact_page, login_page, register_page

# urlpatterns = [
#     url(r'^$', home_page),
#     url(r'^about/$', about_page),
#     url(r'^contact/$', contact_page),
#     url(r'^login/$', login_page),
#     url(r'admin/', admin.site.urls),
# ]
urlpatterns = [
    url(r'^$', home_page, name='home'),
    url(r'^about/$', about_page, name='about'),
    url(r'^contact/$', contact_page, name='contact'),
    url(r'^login/$', login_page, name = 'login'),
    url(r'^cart/', include(("carts.urls",'carts'), namespace='cart')),
    url(r'^register/$', register_page, name='register'),
    url(r'^bootstrap/$', TemplateView.as_view(template_name='bootstrap/example.html')),
    url(r'^products/', include("products.urls", namespace=None)),
    url(r'^search/', include(('search.urls', 'search'), namespace='search')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/search/urls.py
from django.conf.urls import url


from .views import SearchProductView


urlpatterns = [
    url(r'^$', SearchProductView.as_view(), name='query'),
 ]

src/templates/base/css.html
{% load static %}
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

<!-- Fontawesome CSS -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">

src/templates/base/js.html
{% load static %}
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

src/templates/base/navbar.html
{% url 'home' as home_url %}
{% url 'products' as product_list_url %}
{% url 'contact' as contact_url %}
{% url 'about' as about_url %}
{% load static %}

<<<<<<< HEAD

=======
>>>>>>> 23181ea5e2a22513cfd099a19227eac9976f9e35
<nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="{{ home_url }}"><!-- {% if brand_name %}{{ brand_name }}{% else %} eCommerce {% endif %}</a> -->
  <div class ='container'>
   <img src="{% static 'img/logo.jpg' %}" width="30" height="30" class="d-inline-block align-top" alt="">MyBookSeller</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {% if request.path == home_url %}active{% endif %}">
        <a class="nav-link" href="{{ home_url }}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item {% if request.path == product_list_url %}active{% endif %}">
        <a class="nav-link" href="/products/">Products</a>
      </li>
<<<<<<< HEAD
      <!-- <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li> -->
=======
      <li class="nav-item">
        <a class="nav-link" href="/search/?t=top_sellers">Top Sellers</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Genre
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="/search/?g=Fiction">Fiction</a>
          <a class="dropdown-item" href="/search/?g=Science Fiction">Science Fiction</a>
          <a class="dropdown-item" href="/search/?g=Romance">Romance</a>
        </div>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Ratings
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="/search/?r=5">5 stars</a>
          <a class="dropdown-item" href="/search/?r=4">4 stars</a>
          <a class="dropdown-item" href="/search/?r=3">3 stars</a>
          <a class="dropdown-item" href="/search/?r=2">2 stars</a>
          <a class="dropdown-item" href="/search/?r=1">1 stars</a>
        </div>
      </li>
      
>>>>>>> 23181ea5e2a22513cfd099a19227eac9976f9e35
      <li class="nav-item {% if request.path == contact_url %}active{% endif %}">
        <a class="nav-link " href="{{ contact_url }}">Contact</a>
      </li>
      <li class="nav-item {% if request.path == about_url %}active{% endif %}">
        <a class="nav-link " href="{{ about_url }}">About</a>
      </li>
      <li class="nav-item {% if request.path == about_url %}active{% endif %}">
        <a class="nav-link " href="/cart/"> <i class="fas fa-shopping-cart"></i></a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      {% if request.user.is_authenticated %}
      <a class="nav-link " href="{% url 'login' %}">Log-out</a>
      {% else %}	
      <a class="nav-link " href="{% url 'login' %}">Log-in</a>
      <a class="nav-link " href="{% url 'register' %}">Register</a>
      {% endif %}
    </form>
    <form method='GET' action='{% url "search:query" %}' class="form-inline my-2 my-lg-0">
      <div class='input-group'>
          <input class="form-control" type="search" placeholder="Search"  name='q' aria-label="Search">
          <span class='input-group-btn'>
              <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </span>
      </div>
    </form>
  </div>  
</div>
</nav>