src/books/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

from carts.views import *

from .views import home_page, about_page, contact_page, login_page, register_page

# urlpatterns = [
#     url(r'^$', home_page),
#     url(r'^about/$', about_page),
#     url(r'^contact/$', contact_page),
#     url(r'^login/$', login_page),
#     url(r'admin/', admin.site.urls),
# ]
urlpatterns = [
    url(r'^$', home_page, name='home'),
    url(r'^about/$', about_page, name='about'),
    url(r'^contact/$', contact_page, name='contact'),
    url(r'^login/$', login_page, name = 'login'),
    url(r'^cart/', include(("carts.urls",'carts'), namespace='cart')),
    url(r'^register/$', register_page, name='register'),
    url(r'^bootstrap/$', TemplateView.as_view(template_name='bootstrap/example.html')),
    url(r'^products/', include("products.urls", namespace=None)),
    url(r'^search/', include(('search.urls', 'search'), namespace='search')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/carts/urls.py
from django.conf.urls import url


from .views import cart_home, cart_update


urlpatterns = [
    url(r'^$', cart_home, name='home'),
    url(r'^update/$', cart_update, name='update'),
]

src/products/urls.py
from django.conf.urls import url


from .views import ProductListView, ProductDetailSlugView


urlpatterns = [
    url(r'^$', ProductListView.as_view(), name='list'),
    url(r'^(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view(), name='detail'),
]

src/products/models.py
import random
import os
from django.db import models
from django.db.models.signals import pre_save
from .utils import unique_slug_generator
from django.urls import reverse

def get_filename_ext(filepath):
	base_name = os.path.basename(filepath)
	name, ext = os.path.splitext(base_name)
	return name, ext

def upload_image_path(instance, filename):
	new_filename = random.randint(1, 395747514215)
	name, ext = get_filename_ext(filename)
	final_filename = '{new_filename}{ext}'.format(new_filename=new_filename, ext=ext)
	return "products/{new_filename}/{final_filename}".format(new_filename=new_filename, final_filename=final_filename)

class ProductManager(models.Manager):
	def get_by_id(self, id):
		qs = self.get_queryset().filter(id=id)
		if qs.count() == 1:
			return qs.first()
		return None

class Product(models.Model):
	title		= models.CharField(max_length=120)
<<<<<<< HEAD
	slug		= models.SlugField(blank=True, unique=True)
	description = models.TextField()
	price		= models.DecimalField(decimal_places=2, max_digits=10, default=100.00)
	image		= models.ImageField(upload_to=upload_image_path, null=True, blank=True)
	#image		= models.FileField(upload_to='products/', null=True, blank=True)
	quantity 	= models.IntegerField(default=1)
=======
	author		= models.CharField(max_length=120, default='Unknown')
	genre		= models.CharField(max_length=120, default='Unknown')
	slug		= models.SlugField(blank=True, unique=True)
	description = models.TextField()
	rate		= models.IntegerField(default=0, max_length=5)
	price		= models.DecimalField(decimal_places=2, max_digits=10, default=100.00)
	image		= models.ImageField(upload_to=upload_image_path, null=True, blank=True)
	#image		= models.FileField(upload_to='products/', null=True, blank=True)
<<<<<<< HEAD
	amountsold	= models.IntegerField(default=0)


=======
	quantity 	= models.IntegerField(default=1)
>>>>>>> cf3f1fa42fbdb97611b217391bbba9f449c17ff7
>>>>>>> 23181ea5e2a22513cfd099a19227eac9976f9e35
	featured	= models.BooleanField(default=False)  # also can be Best Seller


	objects = ProductManager()

	def get_absolute_url(self):
		return "/products/{slug}/".format(slug=self.slug)
		#return reverse("products:detail", kwargs={"slug":self.slug})

	def __str__(self):
		return self.title

def product_pre_save_receiver(sender, instance, *args, **kwargs):
	if not instance.slug:
		instance.slug = unique_slug_generator(instance)

<<<<<<< HEAD
pre_save.connect(product_pre_save_receiver, sender=Product)
=======
pre_save.connect(product_pre_save_receiver, sender=Product)
>>>>>>> 23181ea5e2a22513cfd099a19227eac9976f9e35

src/products/views.py
from django.http import Http404
from django.views.generic import ListView, DetailView
from django.shortcuts import render, get_object_or_404
from .models import Product
from carts.models import Cart
<<<<<<< HEAD
=======
from django.db.models import F
>>>>>>> 23181ea5e2a22513cfd099a19227eac9976f9e35

class ProductFeaturedListView(ListView):
	template_name = "products/list.html"

	def get_queryset(self, *args, **kwargs):
		request = self.request
		return Product.objects.all()

class ProductFeaturedDetailView(DetailView):
	#queryset = Product.objects.all()
	template_name = "products/featured-detail.html"

	def get_queryset(self, *args, **kwargs):
		request = self.request
		return Product.objects.all()



class ProductListView(ListView):
	template_name = "products/list.html"

	def get_queryset(self, *args, **kwargs):
		request = self.request
<<<<<<< HEAD
=======
		method_dict = request.GET
		query4 = method_dict.get('s', None)
		if query4 is not None and query4=="titleASC":
			return Product.objects.all().order_by(F("title").asc())
		elif query4 is not None and query4=="titleDESC":
			return Product.objects.all().order_by(F("title").desc())
		elif query4 is not None and query4=="authorASC":
			return Product.objects.all().order_by(F("author").asc())
		elif query4 is not None and query4=="authorDESC":
			return Product.objects.all().order_by(F("author").desc())
		elif query4 is not None and query4=="priceLH":
			return Product.objects.all().order_by(F("price").asc())
		elif query4 is not None and query4=="priceHL":
			return Product.objects.all().order_by(F("price").desc())
		elif query4 is not None and query4=="rateHL":
			return Product.objects.all().order_by(F("rate").asc())
		elif query4 is not None and query4=="rateLH":
			return Product.objects.all().order_by(F("rate").desc())
>>>>>>> 23181ea5e2a22513cfd099a19227eac9976f9e35
		return Product.objects.all()

	# def get_context_data(self, *args, **kwargs):
	# 	context = super(ProductListView, self).get_context_data(*args, **kwargs)
	# 	return context

def product_list_view(request):
	queryset = Product.objects.all()
	context = {
		'object_list': queryset
	}
	return render(request, "products/list.html", context)

class ProductDetailSlugView(DetailView):
	queryset = Product.objects.all()
	template_name = "products/detail.html"

	def get_context_data(self, *args, **kwargs):
		context = super(ProductDetailSlugView, self).get_context_data(*args, **kwargs)
		cart_obj, new_obj = Cart.objects.new_or_get(self.request)
		context['cart'] = cart_obj
		return context


	def get_object(self, *args, **kwargs):
		request = self.request
		slug= self.kwargs.get('slug')
		#instance = get_object_or_404(Product, slug=slug)
		try:
			instance = Product.objects.get(slug=slug)
		except Product.DoesNotExist:
			raise Http404("Not found ...")
		except Product.MultipleObjectsReturned:
			qs = Product.objects.filter(slug=slug)
			instance = qs.first()
		except:
			raise Http404("Something unexpected happened :(")
		return instance

class ProductDetailView(DetailView):
	#queryset = Product.objects.all()
	template_name = "products/detail.html"

	def get_context_data(self, *args, **kwargs):
		context = super(ProductDetailView, self).get_context_data(*args, **kwargs)
		return context

	def get_object(self, *args, **kwargs):
		request = self.request
		pk= self.kwargs.get('pk')
		instance = Product.objects.get_by_id(pk)
		if instance is None:
			raise Http404("Product does not exist")
		return instance

	# def get_queryset(self, *args, **kwargs):
	# 	request = self.request
	# 	pk= self.kwargs.get('pk')
	# 	return Product.objects.filter(pk=pk)

def product_detail_view(request, pk=None, *args, **kwargs):
	#instance = Product.objects.get(pk=pk)
	#instance = get_object_or_404(Product, pk=pk)

	instance = Product.objects.get_by_id(pk)
	if instance is None:
		raise Http404("Product does not exist")
	# print(instance)

	# qs = Product.objects.filter(id=pk)
	# if qs.exists() and qs.count()==1:
	# 	instance = qs.first()
	# else:
	# 	raise Http404("Product does not exist")
	cart_obj, new_obj = Cart.objects.new_or_get(request)

	print(cart_obj, new_obj)
	context = {
		'object': instance,
		'cart': cart_obj,
		'new_cart': new_cart,
		'in_cart':False
	}
	if instance in cart_obj:
		print("Exists")
		context['in_cart'] = True
	else:
		print("Does Not Exist")
		context['in_cart'] = False

	return render(request, "products/detail.html", context)



def update_quantity(request, pk=None, *args, **kwargs):
	print(request)


# def change_product_quantity(request)

src/products/templates/products/snippets/card.html
<div class="card" style="width: 15rem;">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
      <style>
      .checked {
          color: orange;
      }
      </style>
  
   {% if instance.image %}
    <a href="{{ instance.get_absolute_url }}">
      <img class="card-img-top" src="{{ instance.image.url }}" alt="{{ instance.title }} logo">
    </a>	
   {% endif %}
    <div class="card-body">
<<<<<<< HEAD
      <h5 class="card-title">{{ instance.title }}</h5>
      <p class="card-text">{{ instance.description|truncatechars:50 }}</p>
      <h5>Customer's Rating</h5>
=======
      <h6 class="card-title">{{ instance.title }}</h5>
      <h6> By {{ instance.author }}</h6>
      <p class="card-text">{{ instance.description|truncatechars:50 }}</p>
      <h6>Customer's Rating</h5>
>>>>>>> 23181ea5e2a22513cfd099a19227eac9976f9e35
    <span class="fa fa-star checked"></span>
    <span class="fa fa-star checked"></span>
    <span class="fa fa-star checked"></span>
    <span class="fa fa-star"></span>
    <span class="fa fa-star"></span>
  </br></br>
      <a href="{{ instance.get_absolute_url }}" class="btn btn-primary">View</a>
      <!-- Testing adding to the cart from the products page -->
      <!-- {% if product in cart.products.all %}
      {% include 'products/snippets/update-cart.html' with product=instance cart=cart in_cart=True %}
      {% else %}
      {% include 'products/snippets/update-cart.html' with product=instance cart=cart in_cart=False %}
      {% endif %} -->

    </div>
  </div>

  

src/products/templates/products/snippets/checkout.html
                <br>
                <button type='submit' class='btn btn-success btn-lg my-3 px-5' style="padding:10px;cursor: pointer;">
                    <a href="repos/src/github.com/take2/src/carts/templates/carts/thank-you.html"></a>
                    <i class="fas fa-check"></i>
                    <i class="fas fa-sign-out-alt"></i>
                </button>

src/products/templates/products/snippets/decrease-quantity.html
<form method='POST' action='{% url "cart:update" %}' class="form"> {% csrf_token %}
        
        <input type='hidden' name='update-quantity' value ='Decrease' />

        <input type="hidden" name="product_id" value='{{ product.id }}'/>

        <button type='submit' class='btn'><i class="fas fa-angle-down"></i></button>
</form>

src/products/templates/products/snippets/increase-quantity.html
<form method='POST' action='{% url "cart:update" %}' class="form"> {% csrf_token %}
        
        <input type='hidden' name='update-quantity' value ='Increase' />

        <input type="hidden" name="product_id" value='{{ product.id }}'/>

        <button type='submit' class='btn'><i class="fas fa-angle-up"></i></button>
</form>
<!-- <form method='POST' action='{% url "cart:update" %}' class="form"> {% csrf_token %}
        <input type='hidden' name='product_id' value ='+' />
        <button type='submit' class='btn'><i class="fas fa-arrow-down"></i></button>
</form> -->

src/products/templates/products/snippets/remove.html
<form method='POST' action='{% url "cart:update" %}' class="form"> {% csrf_token %}
        
        <input type='hidden' name='Wishlist' value ='Remove' />

        <input type="hidden" name="product_id" value='{{ product.id }}'/>

        <button type='submit' class='btn btn-link btn-sm' style="padding:0px;cursor: pointer;">Add back to cart</button>
</form>

src/products/templates/products/snippets/save.html
<form method='POST' action='{% url "cart:update" %}' class="form"> {% csrf_token %}
        
        <input type='hidden' name='Wishlist' value ='Add' />

        <input type="hidden" name="product_id" value='{{ product.id }}'/>

        <button type='submit' class='btn btn-link btn-sm' style="padding:0px;cursor: pointer;">Add to wishlist</button>
</form>

src/products/templates/products/snippets/update-cart.html
<form method='POST' action='{% url "cart:update" %}' class="form"> {% csrf_token %}
    <input type='hidden' name='product_id' value ='{{ product.id  }}' />
    
    {% if in_cart %}
        <button type='submit' class='btn btn-link btn-sm' style="padding:0px;cursor: pointer;">Remove</button>

    {% else %}
        {% if product in cart.products.all %}
            In Cart <button type='submit' class='btn btn-link  my-3 px-5'>Remove?</button>
        {% else %}
            <button type='submit' class='btn btn-success btn-lg my-3 px-5' style="padding:10px;cursor: pointer;">Add to Cart</button>
        {% endif %}
    {% endif %}
</form>